import { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Incidunt
          pariatur rem molestiae repellat temporibus. Perferendis, quas, facilis
          officia et voluptatibus deleniti dignissimos magni, cum sint ad quis
          delectus rem. Quo.
        </p>
      </main>
    </>
  );
};

export default Home;
